SECRET_KEY="@#$%PLMNBHUYTFCXZSE&*"
SQLALCHEMY_DATABASE_URI="mysql://fuzzy:fuzzify@localhost:3306/fuzzy"
SQLALCHEMY_TRACK_MODIFICATIONS=False


MONGODB_DB = "fuzzy"
MONGODB_HOST = "127.0.0.1"
MONGODB_PORT = 27017
MONGODB_USERNAME = "fuzzy"
MONGODB_PASSWORD = "fuzzify"
