"""empty message

Revision ID: 1ba415ecfdf6
Revises: e6ea0f988f08
Create Date: 2017-06-06 14:39:25.211896

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = '1ba415ecfdf6'
down_revision = 'e6ea0f988f08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('skills', app.models.JsonEncodedDict(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'skills')
    # ### end Alembic commands ###
