"""empty message

Revision ID: 2ec9ef73587e
Revises: f467b3796976
Create Date: 2017-06-04 11:40:26.289514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec9ef73587e'
down_revision = 'f467b3796976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobs_email', table_name='jobs')
    op.create_index(op.f('ix_jobs_email'), 'jobs', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_email'), table_name='jobs')
    op.create_index('ix_jobs_email', 'jobs', ['email'], unique=True)
    # ### end Alembic commands ###
