"""empty message

Revision ID: 8fbee3d501fb
Revises: 2ec9ef73587e
Create Date: 2017-06-04 13:29:11.219026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fbee3d501fb'
down_revision = '2ec9ef73587e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('company', sa.String(length=60), nullable=True))
    op.create_index(op.f('ix_jobs_company'), 'jobs', ['company'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_company'), table_name='jobs')
    op.drop_column('jobs', 'company')
    # ### end Alembic commands ###
