"""empty message

Revision ID: a8fc06a47bdf
Revises: 19ec02466227
Create Date: 2017-06-06 20:30:29.688765

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = 'a8fc06a47bdf'
down_revision = '19ec02466227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('expertise', app.models.JsonEncodedDict(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'expertise')
    # ### end Alembic commands ###
