"""empty message

Revision ID: f467b3796976
Revises: a586e9faa8b6
Create Date: 2017-06-04 00:42:06.492500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f467b3796976'
down_revision = 'a586e9faa8b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('position', sa.String(length=60), nullable=True))
    op.create_index(op.f('ix_jobs_position'), 'jobs', ['position'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_position'), table_name='jobs')
    op.drop_column('jobs', 'position')
    # ### end Alembic commands ###
